services:
  redis:
    container_name: redis
    restart: unless-stopped
    networks:
      - redis_network

  init:
    image: ghcr.io/mountain-contractors-supply/pimcore/init:dev
    pull_policy: always
    env_file:
      - .env.dev
    volumes:
      - pimcore-application-logger:/var/www/html/var/application-logger
      - pimcore-email:/var/www/html/var/email
      - pimcore-log:/var/www/html/var/log
      - pimcore-recyclebin:/var/www/html/var/recyclebin
      - pimcore-tmp:/var/www/html/var/tmp
      - pimcore-versions:/var/www/html/var/versions
      - pimcore-assets:/var/www/html/public/var/assets
      - pimcore-public-tmp:/var/www/html/public/var/tmp
    networks:
      - internal_network
      - redis_network
      - opensearch_network

  php:
    image: ghcr.io/mountain-contractors-supply/pimcore/php:dev
    pull_policy: always
    restart: unless-stopped
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=dev.beta.pimcore.mountainland.com
      - LETSENCRYPT_HOST=dev.beta.pimcore.mountainland.com
    env_file:
      - .env.dev
    volumes:
      - pimcore-application-logger:/var/www/html/var/application-logger
      - pimcore-email:/var/www/html/var/email
      - pimcore-log:/var/www/html/var/log
      - pimcore-recyclebin:/var/www/html/var/recyclebin
      - pimcore-tmp:/var/www/html/var/tmp
      - pimcore-versions:/var/www/html/var/versions
      - pimcore-assets:/var/www/html/public/var/assets
      - pimcore-public-tmp:/var/www/html/public/var/tmp
      - /mnt/website_files:/mnt/website_files:ro
    networks:
      - internal_network
      - redis_network
      - nginx_network
      - opensearch_network
      - mercure_network

  supervisord:
    image: ghcr.io/mountain-contractors-supply/pimcore/supervisord:dev
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - pimcore-application-logger:/var/www/html/var/application-logger
      - pimcore-email:/var/www/html/var/email
      - pimcore-log:/var/www/html/var/log
      - pimcore-recyclebin:/var/www/html/var/recyclebin
      - pimcore-tmp:/var/www/html/var/tmp
      - pimcore-versions:/var/www/html/var/versions
      - pimcore-assets:/var/www/html/public/var/assets
      - pimcore-public-tmp:/var/www/html/public/var/tmp
      - /mnt/website_files:/mnt/website_files:ro
    networks:
      - internal_network
      - redis_network
      - opensearch_network
      - mercure_network

  opensearch:
    container_name: ${APP_NAME}-opensearch
    networks:
      - internal_network
      - opensearch_network

  mercure:
    container_name: ${APP_NAME}-mercure
    networks:
      - internal_network
      - mercure_network

# All volumes are declared external so that they are unaffected by blue/green deployments
volumes:
  pimcore-application-logger:
    external: true
  pimcore-email:
    external: true
  pimcore-log:
    external: true
  pimcore-recyclebin:
    external: true
  pimcore-tmp:
    external: true
  pimcore-versions:
    external: true
  pimcore-assets:
    external: true
  pimcore-public-tmp:
    external: true
  website_files:
    external: true

networks:
  internal_network:
  redis_network:
    external: true
  nginx_network:
    external: true
  opensearch_network:
    external: true
  mercure_network:
    external: true
